### ISSUE TITLE
Substitute the ROOT display by "pure" Python

### ISSUE THREAD

**Issue by DFreireF** [DFreireF/rionid#7]
Maybe is a good idea. I feel that maybe the label display will be faster. Although, ROOT is really handy

**Comment by xaratustrah** [comment]
yes, using [adjustText](https://github.com/Phlya/adjustText). I am just commenting, so that I myself not forget!

**Comment by DFreireF** [comment]
Done with [pyqtgraph](https://pyqtgraph.readthedocs.io/en/latest/index.html)
